### ISSUE TITLE
Entity no longer has a state class

### ISSUE THREAD

**Issue by ThomasPrior** [pantherale0/haanglianwater#125]
## System Information

version | core-2025.4.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.13.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/London
config_dir | /config

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After upgrading to 2025.4.3, the Settings section shows an alert:

```The entity no longer has a state class

 We have generated statistics for 'METER_ID Yesterday Cost' (sensor.METER_ID_yesterday_cost) in the past, but it no longer has a state class, therefore, we cannot track long term statistics for it anymore.

Statistics cannot be generated until this entity has a supported state class.

    If the state class was previously provided by an integration, this might be a bug. Please report an issue.
    If you previously set the state class yourself, please correct it. The different state classes and when to use which can be found in the developer documentation.
    If the state class has permanently been removed, you may want to delete the long term statistics of it from your database.

Do you want to permanently delete the long term statistics of sensor.METER_ID_yesterday_cost from your database? ```

### Reproduction steps

1.  Upgrade to haanglianwater 2025.4.3
2.  Observe alert
3. Try pressing "delete" but observe that this does not resolve the issue.
...


### Debug logs

```text
2025-04-30 10:02:40.475 DEBUG (MainThread) [pyanglianwater.auth] Request to https://apims-waf.awis.systems/myaccount/v1/accounts/REDACTED/usage/smartmeter/frequency/10 returned with status 200
2025-04-30 10:02:40.487 DEBUG (MainThread) [custom_components.anglian_water.entity] Updating statistics for sensor.METER_ID_yesterday_consumption
2025-04-30 10:02:40.488 DEBUG (MainThread) [custom_components.anglian_water.entity] Updating statistics for sensor.METER_ID_yesterday_cost
2025-04-30 10:02:40.488 DEBUG (MainThread) [custom_components.anglian_water.entity] Updating statistics for sensor.METER_ID_latest_reading
2025-04-30 10:02:40.489 DEBUG (MainThread) [custom_components.anglian_water.entity] Updating statistics for sensor.METER_ID_latest_cost
2025-04-30 10:02:40.503 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 0.865 seconds (success: True)
2025-04-30 10:02:40.503 INFO (MainThread) [homeassistant.components.sensor] Setting up anglian_water.sensor
```

**Comment by pantherale0** [comment]
Fixed in commit https://github.com/pantherale0/haanglianwater/commit/dd64f815ba85f24b2d448348f3448302ee6812b6

**Comment by ThomasPrior** [comment]
That was fast! Thank you

**Comment by Croft5** [comment]
Hi, Sorry I am not technical. Is there a way for me to fix this or do I need to wait for an update?

Thanks

**Comment by L81ker** [comment]
i see the same issue. Deleting long term stats doesn't resolve it.

should probably be state class total (https://developers.home-assistant.io/blog/2021/09/20/state_class_total?_highlight=state&_highlight=class)

![Image](https://github.com/user-attachments/assets/e42adee0-a344-48f5-a4d0-a055f3b2e637)

**Comment by pantherale0** [comment]
this will be fixed in the next version - the latest beta was pushed before the above commit I referenced was created.

**Comment by pantherale0** [comment]
Fixed in 2025.6.0
